### ISSUE TITLE
Index out of bounds error when decoding 1-bit image with IDENTITY

### ISSUE THREAD

**Issue by abonander** [image-rs/image-png#140]
Ran into this when working on an example for #139 (using current API instead of the replacement):

```rust
    use std::fs::File;
    use png::{Decoder, HasParameters, Transformations};

    // transformations omitting EXPAND will produce indexed bytes for paletted images
    let transformations = Transformations::IDENTITY;

    // any image in pngsuite ending with "3pXX" is a paletted image
    let mut decoder = Decoder::new(File::open("tests/pngsuite/basi3p01.png").unwrap());
    decoder.set(transformations);

    let (_, mut reader) = decoder.read_info().unwrap();
    let mut buf = vec![0u8; reader.output_buffer_size()];
    reader.next_frame(&mut buf).unwrap();

    let palette = reader.info().palette.as_ref().unwrap();

    // these asserts are not reached
    assert_eq!(palette[buf[0] as usize], 238);
    assert_eq!(palette[buf[1] as usize], 0);
```

This panics with the following message and backtrace:

```
thread 'non_expanded_paletted' panicked at 'index out of bounds: the len is 128 but the index is 256', src/utils.rs:162:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:208
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:61
   9: png::utils::expand_pass
             at src/utils.rs:176
  10: png::decoder::Reader<R>::next_frame
             at ./src/decoder/mod.rs:267
  11: non_expanded_paletted::non_expanded_paletted
             at tests/non_expanded_paletted.rs:15
  12: non_expanded_paletted::non_expanded_paletted::{{closure}}
             at tests/non_expanded_paletted.rs:2
  13: core::ops::function::FnOnce::call_once
             at /rustc/d35181ad8785fa958e43580a29a982afe02c728f/src/libcore/ops/function.rs:231
  14: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/d35181ad8785fa958e43580a29a982afe02c728f/src/liballoc/boxed.rs:704
  15: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  16: test::run_test::run_test_inner::{{closure}}
             at /rustc/d35181ad8785fa958e43580a29a982afe02c728f/src/libstd/panicking.rs:272
             at /rustc/d35181ad8785fa958e43580a29a982afe02c728f/src/libstd/panic.rs:388
             at src/libtest/lib.rs:1468
```

I'd investigate this myself but I have work stuff to do so I may not be able to get to this for a while.

**Comment by abonander** [comment]
So as the backtrace shows this is occurring in `utils::expand_pass()` which has some math that assumes minimum 1 byte per pixel, but that's a faulty assumption here because it's actually 8 pixels to a byte instead. The code that calls this doesn't actually appear to take bit-depth into account at all, so I think this would need some refactoring.

**Comment by Shnatsel** [comment]
Do you have an example of a very small image that triggers this error? I'd like to add it to the fuzzing seeds. The fuzzer coverage is clearly incomplete if this error was not discovered.

**Comment by Shnatsel** [comment]
Ah, fuzzer target is not using `Transformations::IDENTITY`, that's why it hasn't caught this.

**Comment by abonander** [comment]
In my draft PR I have a tentative fix which doesn't panic while decoding but the decoded buffer doesn't have the exact values I'm expecting, though I might have implemented the test wrong (`tests/non_expanded_paletted.rs`).
